name: 'techtest'

on:
  workflow_dispatch:
    inputs:
      candidate_name:
        description: 'Name of the Candidate'
        required: true
        default: 'example'
        type: string

jobs:
  Stage:
    runs-on: ubuntu-latest
    steps:
      - run: gh repo create techtest-${{ github.event.inputs.candidate_name }} --source . --public
        env:
          GH_TOKEN: ${{ secrets.ORG_ADMIN_TOKEN }}
